### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by Bretto** [greim/ng-falcor#1]
I am using Jspm 
```
jspm i npm:ng-falcor

import ngFalcor from 'ng-falcor';
angular
    .module('AppModule', [])
.factory('ngf', ngFalcor.create({
        router: '/model.json',
        cache: {}
    }))
```

and I am getting ```Cannot read property 'create' of undefined```

What module loader are you using ? Am I missing something ?

**Comment by greim** [comment]
Thanks for the issue report. I just published an update (v0.5.4) to npm that hopefully fixes this. Please re-open this issue if you still have any problems.
