### ISSUE TITLE
Atom array serialization

### ISSUE THREAD

**Issue by martin-labrecque** [greim/ng-falcor#13]
We encountered an issue with the way ​**atom**​ arrays are serialized in our server vs the way they are handled by your library.

According to Falcor documentation[1], arrays are serialized to json in the form of an atom, such as: 
`{ $type: "atom", value: ['en', 'fr'] }`

However, in the Java implementation[2] of class AtomSerializer, arrays are not wrapped inside Atom objects. Indeed, only POJO and Objects are wrapped:

```java
	@Override
    public void serializeWithType(Atom value, JsonGenerator gen, SerializerProvider serializers, TypeSerializer typeSer) throws IOException {
        final JsonNode atom = value.asAtom();
        if (atom.isObject() || atom.isPojo()) {
            typeSer.writeTypePrefixForObject(value, gen);
            gen.writeObjectField("value", value.asAtom());
            typeSer.writeTypeSuffixForObject(value, gen);
        } else {
            // Omit type if atom is not an object
            gen.writeTree(value.asAtom());
        }
    }
```

After verification, your library works in the first case but does not work in the second case. What do you think? Would you be able to support both ways?

[1] http://netflix.github.io/falcor/documentation/jsongraph.html#atom

[2] http://mvnrepository.com/artifact/com.netflix.falcor/falcor-model/0.49.0

**Comment by greim** [comment]
Would you mind clarifying your request? Are you saying that a naked array can exist inside the Falcor cache, which should be returned as a primitive value type by ng-falcor, instead of being treated as yet another branch node in the graph?

Also wasn't aware that Netflix has Java client code for Falcor which is open source. Are you using it and/or is it in a workable state?

**Comment by martin-labrecque** [comment]
To answer your last question first, we are using Netflix Java code to build our own implementation of Falcor Router on the server side and we use your library on the client side. I would say the Java code is in a workable state but of course, still subject to change.

To clarify my request, I am not a Falcor expert to say what is right and what is wrong but according to the Java code above (I also tested it personally), an atom array (ex. `['fr', 'en']`) is serialized as a naked array (without `$type: 'atom'` wrapper).
See comment in code: `// Omit type if atom is not an object`
So yes, it seems like an atom array would be treated as a primitive value.

Does that make sense for you or do you think there could be a bug in the Java code of Netflix?
This is misleading since this is not the same information in the official Falcor documentation.

Thanks for your help!

**Comment by greim** [comment]
Interesting. It's hard to know for sure whether that Java code represents the correct behavior since there's no github repo to post questions or anything. What's the desired behavior versus the actual behavior, in terms of actual JS code? For example:

```js
var foo = ngf('foo', 'bar', 'baz');
assert(...?)
```

Thanks

**Comment by martin-labrecque** [comment]
Assuming 'baz' is an atom array (leaf), for instance ['fr','en'], I would expect that `ngf('foo', 'bar', 'baz') `returns a naked array, example ['fr','en'].

The issue occurs when the server returns a naked array (example ['fr','en']) to your library, following `ngf('foo', 'bar', 'baz')`.

Your library keeps performing requests to the server for the same path until it explodes :)
The issue seems to be that the returned value is never cached when that value is not wrapped in an atom object (example: `{ $type: "atom", value: ['en', 'fr'] })`.

To answer your question, we expect the following:

```javascript
var actual = ngf('foo', 'bar', 'baz');
var expected = ['fr','en'];
assert(actual, expected);
```

However, the fix should be done in the way your library handles the server response.

Thanks!

**Comment by greim** [comment]
Ahh, I see. Thanks for the explanation. Unfortunately, the client-server communication piece—which includes the repeated requests until it explodes—is handled purely at the level of interaction between the model and the datasource, which is all Netflix code and beyond my control.

I don't know how the Java stuff works, but in JS-land you have the option to [box values](http://netflix.github.io/falcor/doc/Model.html#boxValues). In your router implementation, would something similar be possible?

**Comment by martin-labrecque** [comment]
Interesting this boxValues thing! I will have a look, thanks!
By the meantime, we managed to find another workaround patch to force the server output a wrapped atom array and it works as expected.

So, my understanding is that, the problem is either Netflix's **Java** library that should return a **wrapped atom array** instead of a naked array OR Netflix's **JS** library that should handle correctly the server response when it contains a **naked atom array**, right?

Thanks again for your help!

**Comment by greim** [comment]
Yup, that's my understanding. Good luck!
