### ISSUE TITLE
Issues with withoutDataSource()

### ISSUE THREAD

**Issue by Bretto** [greim/ng-falcor#3]
I am trying to convert my application to ng-falcor, but the ```withoutDataSource()``` is causing some issues. Do you think you could enable this api ? Basically it should only set the local model when using withoutDataSource().
ie:
```
await _this.falcorModel.withoutDataSource()
                .set(...roomsPath).then((res)=> {
                    console.log('set rooms on itemsById', res);
                });
```

**Comment by greim** [comment]
That method can be exposed by adding `withoutDataSource` here: https://github.com/greim/ng-falcor/blob/5fe7f1b345f01e8002df14e7a70c1f87414516a5/src/index.js#L50-L60

If you'd like to submit a PR, I'll merge it in.

**Comment by Bretto** [comment]
done. thanks
