### ISSUE TITLE
Duplication of Post call with callModel

### ISSUE THREAD

**Issue by Bretto** [greim/ng-falcor#6]
If you have a ```.then``` after the callModel the Post is executed twice
ie:
```
return this.ngF.callModel(
            ["category", categoryId, "items", "push"],
            [newItem],
            ["name", "uid"],
            ["length"]);
            .then((res)=> {
                ... something ...
            });
```
If you omit the ```.then``` you don't get the issue.
This is quite problematic in my app atm, are you experiencing the same behaviour ? Or am I doing something wrong ? On a side note this project is awesome, great job !

```prom.then(noop);``` in thenify.js is causing the issue...

**Comment by greim** [comment]
This should be fixed in 0.5.6, just published to npm.
