### ISSUE TITLE
Path syntax with ngf()

### ISSUE THREAD

**Issue by martin-labrecque** [greim/ng-falcor#7]
The documentation says that the syntax for "ngf()" should be:
`{{ ngf(['usersByUsername', username, 'first_name']) }}`

but in fact, the syntax that is currently working is:
`{{ ngf('usersByUsername', username, 'first_name') }}`

In short, we don't need to add the square brackets [ ] right now.

Is it a code issue or is the documentation simply outdated for this part of information?
Which syntax should be the correct one to use?

By the way, thanks for supporting this library! :)

**Comment by greim** [comment]
It ought to work either way, does it not? I'm considering deprecating the bare args version (`ngf('foo', 'bar')`) and enforcing an array used everywhere (`ngf(['foo', 'bar'])`) for consistency. What do you think?

**Comment by martin-labrecque** [comment]
Thanks for the quick response!

In fact, it doesn't seem to work 100% when the brackets are used.

For instance, if I request:
`{{ ngf(['usersByUsername', "myUsername", 'first_name']) }}`
The path sent to the server seems to be inverted:
`paths:[[["first_name","myUsername","usersByUsername"]]]`

Instead it should be:
`paths:[[["usersByUsername","myUsername","first_name"]]]`

To answer your question, I would prefer using the array/bracket version too.

As a side note, is there a way where we could have general discussions about your library or if we simply have questions (like Gitter)?

**Comment by greim** [comment]
Okay yeah, confirmed it was mis-handling arrays and was able to reduce it to a unit test. Thanks for the catch! Fix published in 0.7.1. Let me know if it doesn't fix your original issue.

I'll consider removing the alternate version in a future release. As for communication, I do pay pretty close attention to GitHub these days so feel free to post questions as issues and I'll do my best to answer them. If it gets overwhelming I'll certainly look at Gitter or something. Thanks again!

**Comment by martin-labrecque** [comment]
Awesome! The problem is fixed.
Thanks @greim !
