### ISSUE TITLE
Issue with ngf.range(0, 0)

### ISSUE THREAD

**Issue by martin-labrecque** [greim/ng-falcor#8]
I have an issue where I want to create a range array to iterate on a list that has a length of 1.
For instance, `ngf.range(0, length - 1)` where length = 1, which in fact results in `ngf.range(0, 0)`.
I would expect to get this array in return [0] but instead I get an empty array [].

I understand that the purpose of this method is to create a range but would it be possible to support a range of one value or would I need to support this specific case myself?
Thanks for your help!

**Comment by greim** [comment]
What version are you on? In the latest version 0.8.6 it seems to behave the way you expect. Here's the unit test I added:

```js
    it('should create a one-length range', () => {
      const factory = create();
      const ngf = factory($rootScope);
      const range = ngf.range(0,0);
      assert.deepEqual(range, [0]);
    });
```

**Comment by martin-labrecque** [comment]
Thanks for your very fast response!
You are right, sorry. My version was a little bit outdated and you seem to have fixed the problem afterward. It works perfectly as expected! :)
I will close this ticket.
Thanks a lot!
